=pod

=encoding UTF-8

=head1 NAME

Epidermis::Lab::Instrument::BeckmanCoulter - Protocols for specific Beckman Coulter instruments

=head1 VERSION

version 0.001

=head1 DESCRIPTION

=over 4

=item * L<Epidermis::Lab::Instrument::BeckmanCoulter::Chemistry::AU480>

=item * L<Epidermis::Lab::Instrument::BeckmanCoulter::Hematology::AcT5diff>

=item * L<Epidermis::Lab::Instrument::BeckmanCoulter::Immunoassay::Access2>

=back

=head1 AUTHOR

Zakariyya Mughal <zmughal@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2020 by Zakariyya Mughal.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
